version: "3.3"
services:
  backend:
    build: .
    volumes:
      - "test_rest_fastapi_volume:/app/database/"
    env_file: app/.env.dist
    ports:
      - 8080:80

  tests:
    build: .
    env_file: app/.env.dist
    environment:
      - APP_ENVIRONMENT=test
    profiles:
      - do_not_start
    command: pytest

volumes:
  test_rest_fastapi_volume: